import streamlit as st
import streamlit.components.v1 as components
st.title("About Us")
st.write("This is the About page.")
st.write("We are a team of passionate developers who love creating web applications using Streamlit and Python.")
st.write("Our goal is to make data science and machine learning accessible to everyone.")
st.write("Feel free to reach out to us if you have any questions or feedback.")
st.write("You can contact us at:")

st.write("Email:kartik.kumar@gmail.com")
st.write("Phone: 9876543210")
st.write("Address: 123 Main St, Anytown, USA")
st.write("Follow us on social media:")
st.write("Twitter: [@example](https://twitter.com/example)")
st.write("LinkedIn: [example](https://linkedin.com/in/example)")
st.write("GitHub: [example](https://github.com/example)")
st.write("Facebook: [example](https://facebook.com/example)")   
st.write("Instagram: [example](https://instagram.com/example)")
st.write("YouTube: [example](https://youtube.com/example)")
st.write("TikTok: [example](https://tiktok.com/@example)")
st.write("Snapchat: [example](https://snapchat.com/add/example)")
st.write("Pinterest: [example](https://pinterest.com/example)")
st.write("Reddit: [example](https://reddit.com/user/example)")
st.write("Discord: [example](https://discord.gg/example)")
st.write("WhatsApp: [example](https://wa.me/example)")
st.write("Telegram: [example](https://t.me/example)")
st.write("We look forward to hearing from you!")
st.write("Thank you for visiting our website!")